spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ebenezerlewis21/esoft-7card-server.git
          default-label: main
          search-paths: '{application}'
          clone-on-start: true
