spring:
  datasource:
    url: ${DEV_DB_URL:jdbc:postgresql://localhost:5432/esoft_dev}
    username: ${DEV_DB_USERNAME:postgres}
    password: ${DEV_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    root: INFO
